### ISSUE TITLE
Wrong shortest path matrix returned  when using Floyd-Warshal GPU algorithm on Large Graph (N>=3300)

### ISSUE THREAD

**Issue by wariobrega** [mazzalab/pyntacle#19]
When using the `shortest_path_gpu` method on a large graph (with more than 3000 nodes) the shortest path matrix is either returned incorrect  (on Linux machines) or it raises a `CUDA_UNKOWN_ERROR` on a Windows based machine.

**_Setups:_**

**Linux machine:**

- Graphic device: NVIDIA GeForce GTX 1050 Ti
- Cuda version= 10.0
 

**Windows:**

- NVIDIA Quadro 
- Cuda version = 8.0

**Comment by mazzalab** [comment]
Issue solved with new implementation of shortest path gpu in commit `ec0734d`
