### ISSUE TITLE
gr-finder bruteforce test fails

### ISSUE THREAD

**Issue by mtruglio** [mazzalab/pyntacle#25]
For some reason, "gr-finder bruteforce" fails as a test when included in the test suite, but it works if tested by itself or with the other gr tests only.

In addition, if uncommented, it also makes the "test_global" metrics test fail. This test compares the results of the same analysis executed with cpu, igraph and gpu implementation. If one of the first two is skipped, it does not fail anymore.

These glitches don't seem to have any impact on Pyntacle's commands and results when executed normally, but could be a warning sign about memory management weirdness during the execution of brute-force algorithms.

**Comment by mazzalab** [comment]
I've now run tests on my installation (Windows), and all tests complete successfully. Could you retry before the next 1.2 release?

**Comment by mtruglio** [comment]
All good here! The "memory problem" causing this was apparently solved somewhere else.
