### ISSUE TITLE
Centrality Measures for Weighted graphs?

### ISSUE THREAD

**Issue by alexberd** [mazzalab/pyntacle#26]
Hi all.

I recently tested Pyntacle and found to be really quick and easy to use for large datasets due to its GPU functionallity! Great tool thanks a lot for the support @mazzalab!

I wish it had also functionality for weighted graphs. How easy and possible is to add this to its core methods? This would massively increase its use!

Many thanks.
Alexandros

**Comment by mazzalab** [comment]
Hi Alexandros,
thanks for using our piece of research.

For some reason, we have initially relied on iGraph as a graph manager and a future attempt will be that of shaping and implementing our own internal graph data structure manager to smoothly replace it. With it, we will face the problem of weighted graphs first (in 2020) and direct graphs later.

We will let you know about Pyntacle's developments, that anyway will be available also from its page in ResearchGate (https://www.researchgate.net/project/Pyntacle-A-high-performance-framework-for-the-analysis-of-team-play-effect-in-biological-networks)

a presto,
- tommaso
