### ISSUE TITLE
WARNING: test_convert_dot

### ISSUE THREAD

**Issue by mazzalab** [mazzalab/pyntacle#29]
the test: 
`suite.addTest(WidgetTestConvert('test_convert_dot'))` 
in test_suite.py, raises the following warning messages

\pyntacle\io_stream\exporter.py:236: RuntimeWarning: A boolean graph attribute was converted to numeric at src\foreign.c:2853
  Graph.write_dot(graph, f=file)
\pyntacle\io_stream\exporter.py:236: RuntimeWarning: A non-numeric, non-string graph attribute ignored at src\foreign.c:2940
  Graph.write_dot(graph, f=file)
\pyntacle\io_stream\exporter.py:236: RuntimeWarning: A boolean edge attribute was converted to numeric at src\foreign.c:2938
  Graph.write_dot(graph, f=file)

It is (maybe) caused by graph/edge/vertex attributes initialized to NONE that cannot be serialized

**Comment by mtruglio** [comment]
This is a warning caused by a c library which takes care of handling .dot conversion. Nothing major, no effect on the results of the test.
