### ISSUE TITLE
Pyntacle import error

### ISSUE THREAD

**Issue by omairzkhan** [mazzalab/pyntacle#45]
Hello there,

I am hoping to use Pyntacle for a research project but I'm having some trouble importing it.

I get the error "ModuleNotFoundError: No module named 'numba.core'" (see screenshot). However, numba is installed. See second screenshot for numba version (0.41.0). My machine is running Windows 10 -- see third screenshot for more detailed system information. 

"pyntacle test" ran fine (I think) The results of that command are in the fourth screenshot. 

Thanks very much for any help you can provide!

![image](https://user-images.githubusercontent.com/62121482/89956945-17b8b580-dbeb-11ea-8da0-0715f6bef231.png)

![image](https://user-images.githubusercontent.com/62121482/89956969-256e3b00-dbeb-11ea-91a2-6578526e88f2.png)

![image](https://user-images.githubusercontent.com/62121482/89957001-35861a80-dbeb-11ea-914f-8ff390490a4c.png)

![image](https://user-images.githubusercontent.com/62121482/89956924-040d4f00-dbeb-11ea-8336-569104421f7f.png)

**Comment by mazzalab** [comment]
Hi, can you give us more information on how you installed Pyntacle? 

It seems you have an old version of numba. The latest version should be the 0.50, which has recently changed some module names and Pyntacle dependends on the latest version. 

That might be the source of your error

**Comment by omairzkhan** [comment]
Thanks very much, mazzalab! That was indeed the issue--upgrading to numba 0.50.1 allowed me to import pyntacle. Thanks again for your help.
