### ISSUE TITLE
[cmd] error in Kp-info

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#47]
Quick start guide notebook

Command used:` pyntacle keyplayer kp-info -i  AdvSeek.adjm -t dF --nodes HB,WD`

error received: AttributeError: `'Namespace' object has no attribute 'nprocs'`

**Comment by mazzalab** [comment]
this error was due to a missing parameter (--nprocs, -O) in the command line parser that, even if useless in this case, would have initialized the number of needed processes for this task to 1 (default choice). It was fixed.
