### ISSUE TITLE
[cmd] error in Kp-finder command

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#48]
Quickstart guide notebook

command used:` pyntacle keyplayer kp-finder -i AdvSeek.adjm -k 2 -m 1 -t mreach`

error: the program return an empty .tsv file

There is the same problem also using the brute-force option

**Comment by mazzalab** [comment]
do you receive an error message? Can you report it here?
Can you open another issue about the brute-force error, reporting the error message also for this?

**Comment by lorenbioinfo** [comment]
it seems there aren't errors. The files are corretly imported and both the plot and the tsv file are generated.

my output:
```
Using greedy optimization algorithm for searching the optimal key player set for the requested key player metrics
Node set size for key-player search: 3
Writing report in txt format
Plotting network and run results in /mypath directory with PyntacleInk
```

**Comment by mazzalab** [comment]
there is actually a bug. You specify mreach in the command line but it matches m-reach inside the code. This cause to leave the last half of the report file empty.
