### ISSUE TITLE
[cmd] error in pyntacle generate command

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#49]
Case study 1 notebook

command used: `pyntacle generate random -n 37 -e 284 -seed 100`

error received :`random: error: argument : invalid choice: '100' (choose from 'random', 'small-world', 'scale-free', 'tree')`

**Comment by mazzalab** [comment]
the error is due to the removed option seed

please update the **case study 1** using this command line:

`pyntacle generate random -n 37 -e 284` <s>-seed 100</s> and thus removing **-seed 100**
