### ISSUE TITLE
[API] error in group degree

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#51]
Case study 2 notebook

Command used: `Octopus.GO_group_degree(graph, 11, seed=seed)`

error received:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-23-67b63df861b9> in <module>
      1 seed = 1
----> 2 Octopus.GO_group_degree(graph, 11, seed=seed)
      3 
      4 graph["group_degree_greedy"]

TypeError: GO_group_degree() got an unexpected keyword argument 'seed'
```

**Comment by mazzalab** [comment]
The argument `seed` was removed from this and all other Pyhtacle's functions. Thus, removing:
this line: `seed = 1`
and the argument: `Octopus.GO_group_degree(graph, 11` <s>, seed=seed</s>)
will solve the issue
