### ISSUE TITLE
[cmd ]Error in Pyntacle converter

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#52]
command line guide

command used:`pyntacle convert -i AdvSeek.adjm -u sif --no-output-header`

output :
```
Running Pyntacle convert
*******************************************  RUN START  ********************************************
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

It returns the same error also with the other input/output format couples

**Comment by mazzalab** [comment]
There was a bug in the parsing of the output file name, that was not inferred, as stated, if not specified. Fixed in the new release.
